// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AliasTarget = { key: string, citation: string, 
/**
 * Original ALR evidence-record identifiers in registry/aliases.json.
 * These are provenance references, never runtime lookup keys.
 */
records: Array<string>, };
