// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pinpointer's alias-index target: a citation or jurisdiction/database/caseId.
 * The path is evidence supplied by the owning CanLII index, not inferred from
 * a case name. Keep the original slug while selecting the published language.
 */
export type AliasTargetInfo = { url: string, year: string, courtId: string | null, };
