// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from "./Annotation";
import type { DiffOperation } from "./DiffOperation";
import type { OffsetUnit } from "./OffsetUnit";
import type { Options } from "./Options";

/**
 * Insert markup into `text`, or into `source` (the markup `text` was cleaned
 * from with `cleanSteps`), preserving the source's tags.
 *
 * Either pass explicit `annotations` (spans of `text` in `offsetUnit`, like
 * eyecite's `annotate_citations`), or leave them out and every citation found
 * in `text` is wrapped in `before`/`after`, templates in which `{index}`,
 * `{key}`, `{form}`, `{authority}` and `{url}` are substituted.
 */
export type AnnotateRequest = { text: string, options: Options, annotations: Array<Annotation> | null, before: string, after: string, 
/**
 * Which extent of each found citation to wrap: `span` (the core,
 * eyecite's `span()`, default) or `fullSpan`.
 */
span: string | null, 
/**
 * Original markup `text` was cleaned from; the result is that markup,
 * annotated. Cleaning `source` with `cleanSteps` must give `text`.
 */
source: string | null, cleanSteps: Array<string>, 
/**
 * Character-count diff steps supplied by a host's stdlib aligner.
 */
alignment: Array<[DiffOperation, number]> | null, 
/**
 * Source spans returned by a host-provided offset updater, in input order
 * and offsetUnit. Ordering still uses the original extraction spans.
 */
sourceOffsets: Array<[number, number]> | null, 
/**
 * How to treat an annotation whose source range crosses tags unevenly
 * (eyecite's `unbalanced_tags`): `unchecked` (default), `skip`, `wrap`.
 */
unbalancedTags: string | null, 
/**
 * Unit of `annotations` offsets.
 */
offsetUnit: OffsetUnit, };
