// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";

/**
 * Why a call failed. Serialized as `{"code": ..., "message": ...}`.
 */
export type ApiError = { code: ErrorCode, message: string, };
