// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A journal article's parts.
 */
export type Article = { authors: Array<string>, title: string, year: string | null, volume: string | null, issue: string | null, journal: string | null, firstPage: string | null, 
/**
 * An online paper's own document citation, used when there is no journal.
 */
docCitation: string | null, };
