// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of authority a citation identifies.
 */
export type Authority = "case" | "statute" | "regulation" | "constitution" | "court_rule" | "treaty" | "bill" | "debate" | "parliamentary_paper" | "government_document" | "journal" | "book" | "book_chapter" | "webpage" | "unknown";
