// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CaseCitationRequest = { texts: Array<string>, language: string | null, fallback: string, provider: string | null, };
