// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AliasTarget } from "./AliasTarget";
import type { Authority } from "./Authority";
import type { CourtRef } from "./CourtRef";
import type { Fields } from "./Fields";
import type { Form } from "./Form";
import type { Format } from "./Format";
import type { History } from "./History";
import type { Interpretation } from "./Interpretation";
import type { Parenthetical } from "./Parenthetical";
import type { Parties } from "./Parties";
import type { Pinpoint } from "./Pinpoint";
import type { Span } from "./Span";

/**
 * One citation found in a text.
 */
export type Citation = { 
/**
 * Position in the returned list; other citations refer to it by this index.
 */
index: number, form: Form, authority: Authority, format?: Format | null, 
/**
 * The citation core: `2016 SCC 27`, `RSC 1985, c C-46`, `Ibid`.
 */
span: Span, 
/**
 * An introductory signal in front of the citation (`See`, `See also`,
 * `Cf`, `But see`, `Voir`), normalized to lowercase without punctuation.
 */
signal?: Span | null, 
/**
 * Style, core, pinpoints, parentheticals and a bracketed short form.
 */
fullSpan: Span, 
/**
 * The style of cause, statute title or author/title in front of the core.
 */
style?: Span | null, parties?: Parties | null, fields: Fields, court?: CourtRef | null, 
/**
 * Registry jurisdiction id: `ca`, `ca-on`, `uk`, `uk-ew`, `au-nsw`, `us`, `us-ca`, ...
 */
jurisdiction?: string | null, 
/**
 * `en` or `fr` when the citation form is language-specific.
 */
language?: string | null, pinpoints?: Array<Pinpoint>, parentheticals?: Array<Parenthetical>, history?: Array<History>, 
/**
 * The name later references use: the observed style, or an explicit
 * bracketed short form (`[Jordan]`).
 */
shortName?: string | null, explicitShortName?: string | null, 
/**
 * Citations to the same decision printed side by side share a group id:
 * the index of the group's first citation.
 */
parallelGroup?: number | null, 
/**
 * For a short form, supra, ibid or reference: the full citation it resolves to.
 */
antecedent?: number | null, 
/**
 * The versioned identity key of the authority (see [`crate::key`]).
 */
key?: string | null, 
/**
 * Evidence-backed reporter parallel, without changing the written fields.
 */
alias?: AliasTarget | null, interpretations?: Array<Interpretation>, 
/**
 * Which grammar rules produced this reading, for audit and debugging.
 */
reasons: Array<string>, };
