// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A citation guide whose forms the finder recognizes beyond the forms every guide shares.
 */
export type CitationStyle = "mcgill" | "coal" | "bluebook" | "aglc" | "oscola" | "nzlsg";
