// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CorrectionKind } from "./CorrectionKind";
import type { CorrectionLayout } from "./CorrectionLayout";
import type { CorrectionMetadata } from "./CorrectionMetadata";

export type CitationCorrection = { text: string, kind: CorrectionKind, style: string | null, jurisdiction: string | null, sourceLayout: CorrectionLayout | null, reporter: string | null, correctedReporter: string | null, page: string | null, metadata: CorrectionMetadata, };
