// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CitationKey = { index: number, 
/**
 * The citation core as written.
 */
text: string, key: string | null, };
