// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CleanRequest = { text: string, 
/**
 * eyecite-compatible step names: `html`, `xml`, `inline_whitespace`,
 * `all_whitespace`, `underscores`, plus `zero_width`; applied in order.
 */
steps: Array<string>, };
