// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eyecite's class-specific corrected-citation operations. The facade supplies
 * its mutable groups and metadata; no parsing or formatting occurs in Python.
 */
export type CorrectionKind = "plain" | "resource" | "case" | "short_case" | "law" | "journal";
