// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CorrectionMetadata = { pin_cite: string | null, plaintiff: string | null, defendant: string | null, extra: string | null, court: string | null, year: string | null, month: string | null, day: string | null, publisher: string | null, parenthetical: string | null, antecedent_guess: string | null, };
