// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A court resolved against the registry.
 */
export type CourtRef = { 
/**
 * Registry id, e.g. `scc`, `onca`, `ewca-civ`, `ca9`.
 */
id: string, 
/**
 * The surface text the court was read from.
 */
text: string, };
