// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCode = "unknown_method" | "invalid_request" | "invalid_offset" | "unimplemented";
