// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExcerptClassification = { kind: string, citeTokens: number, citeRuns: number, citeCharCoverage: number, functionWords: number, proseWindow: string | null, rule: string, };
