// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OffsetUnit } from "./OffsetUnit";
import type { Options } from "./Options";

export type ExtractRequest = { text: string, markupText: string | null, options: Options, 
/**
 * Unit of every offset in the response, and of `options.notes` ranges.
 */
offsetUnit: OffsetUnit, };
