// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";
import type { OffsetUnit } from "./OffsetUnit";
import type { Resolution } from "./Resolution";
import type { SourcePart } from "./SourcePart";

export type ExtractResponse = { schemaVersion: number, offsetUnit: OffsetUnit, citations: Array<Citation>, sourceParts: Array<SourcePart>, authorities: Array<Array<number>>, 
/**
 * How each reference resolved (with `options.resolve`), its source part indexed into
 * `source_parts`: the antecedent of a reference to a book, report or page no citation names.
 */
resolutions: Array<Resolution>, };
