// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InlineReference } from "./InlineReference";
import type { PinpointKind } from "./PinpointKind";
import type { SourceCaseName } from "./SourceCaseName";
import type { SourceEdition } from "./SourceEdition";
import type { Span } from "./Span";

/**
 * Parsed components. Every field is optional; which fields are filled depends
 * on [`Authority`] and [`Format`].
 */
export type Fields = { 
/**
 * Pinned source name metadata, kept separately from the document's styled extent.
 */
sourceCaseName?: SourceCaseName | null, 
/**
 * Named fields from the source extractor, including unmatched optional groups.
 */
sourceGroups?: { [key in string]: string | null }, exactEditions?: Array<SourceEdition>, variationEditions?: Array<SourceEdition>, sourceEdition?: SourceEdition | null, 
/**
 * Additional citation text before a shared court/date parenthetical.
 */
extra?: string | null, 
/**
 * Court surface captured with post-citation metadata, before registry resolution.
 */
courtText?: string | null, 
/**
 * The written pinpoint phrase, including its locator label. Individual
 * `Pinpoint` spans retain their value-only offsets.
 */
pinCite?: Span | null, pinCiteKind?: PinpointKind | null, explicitShortSpan?: Span | null, inlineReference?: InlineReference | null, year?: string | null, 
/**
 * Numeric year accepted by Eyecite (1600 through the current year plus one).
 * The original year text remains in `year`, including dates outside that range.
 */
yearNumber?: number | null, month?: string | null, day?: string | null, volume?: string | null, 
/**
 * The reporter, journal or series abbreviation as written.
 */
reporter?: string | null, 
/**
 * The registry's canonical abbreviation for [`Fields::reporter`].
 */
reporterCanonical?: string | null, 
/**
 * Stable registry reporter id, distinct from its possibly shared abbreviation.
 */
reporterId?: string | null, page?: string | null, 
/**
 * Neutral-citation or database decision number.
 */
number?: string | null, 
/**
 * Neutral court identifier or statute/regulation series as written.
 */
series?: string | null, chapter?: string | null, schedule?: string | null, section?: string | null, regnal?: string | null, regulation?: string | null, edition?: string | null, place?: string | null, publisher?: string | null, bill?: string | null, session?: string | null, body?: string | null, url?: string | null, docket?: string | null, 
/**
 * The note a `supra`/`above n` reference points to.
 */
note?: number | null, 
/**
 * The title of an untitled legislation citation in a note, as the sentence the note hangs
 * from writes it right before the note's marker ("… enacted the Good Samaritan Drug
 * Overdose Act.¹" for "¹ SC 2017, c 4.").
 */
anchorTitle?: Span | null, 
/**
 * The instrument's own name where the citation writes only where it is enacted: the
 * Charter for "Part I of the Constitution Act, 1982, being Schedule B to the Canada Act 1982
 * (UK), 1982, c 11".
 */
instrumentTitle?: string | null, };
