// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The surface shape of a case citation or legislative citation.
 */
export type Format = "neutral" | "reporter" | "can_lii" | "database" | "docket" | "statute_volume" | "regulation_series" | "code" | "publication" | "url";
