// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";
import type { OffsetUnit } from "./OffsetUnit";
import type { Options } from "./Options";
import type { PinpointRequest } from "./PinpointRequest";

/**
 * Format citations (`citation` or every citation in `text`) or a bare
 * pinpoint, in McGill style.
 */
export type FormatRequest = { citation: Citation | null, text: string | null, pinpoint: PinpointRequest | null, options: Options, offsetUnit: OffsetUnit, 
/**
 * Citation style; only `mcgill` (the default) today.
 */
style: string | null, 
/**
 * `en` (default) or `fr`.
 */
language: string | null, 
/**
 * Range separator: `-` (default) or `–` (U+2013).
 */
rangeDash: string | null, };
