// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Formatted = { index: number, 
/**
 * `null` for forms the formatter does not render (short forms,
 * references, unknown).
 */
formatted: string | null, };
