// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a citation refers to its authority.
 */
export type Form = "full" | "short" | "supra" | "ibid" | "reference" | "unknown";
