// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GrammarVersion = { 
/**
 * `legal-grammar-corpus:v1`.
 */
format: string, 
/**
 * Number of grammar entries across all tables.
 */
entries: number, 
/**
 * SHA-256 of the embedded `grammar-corpus.json`.
 */
sha256: string, };
