// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";

/**
 * A subsequent- or prior-history relation: `aff'd`, `rev'd`, `leave to appeal
 * to SCC refused`.
 */
export type History = { 
/**
 * Normalized relation: `affirmed`, `reversed`, `leave_refused`,
 * `leave_granted`, `varied`, `overruled`, `appeal_dismissed`, ...
 */
relation: string, span: Span, 
/**
 * Index of the citation the relation points to, when it was extracted.
 */
target?: number | null, };
