// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";

/**
 * Original inline-reference token, before the broader source-resolution extent.
 */
export type InlineReference = { span: Span, note?: number | null, };
