// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A registry interpretation of an abbreviation shared by several authorities.
 * Alternatives remain visible even when context or a priority selects one.
 */
export type Interpretation = { kind: string, id: string, canonical: string, jurisdiction?: string | null, selected: boolean, reason: string, };
