// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CitationKey } from "./CitationKey";

export type KeyForTextResponse = { keyVersion: string, 
/**
 * The key of the one full citation `text` holds (`R v Jordan, 2016 SCC
 * 27`), per [`crate::key::key_for_text`]; `null` with a `reason` otherwise.
 */
key: string | null, 
/**
 * `no_citation`, `multiple_citations` or `no_identity` when `key` is null.
 */
reason?: string | null, message?: string | null, 
/**
 * Every citation's key in document order; a back reference carries the
 * key of the authority it resolves to.
 */
keys: Array<CitationKey>, };
