// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pinpointer's candidate spellings for its external CanLII TSV index. These
 * are lookup hints, never authority keys or unverified source URLs.
 */
export type LegislationLookup = { candidates: Array<string>, jurisdiction: string, };
