// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Collapse locators into McGill ranges and lists: `12, 13, 14, 20` →
 * `12-14, 20`; `7(2), 7(3), 7(4)` → `7(2)-(4)`. Each `(first, last)` item
 * is a single locator (`last` = `None`) or an explicit range.
 */
export type LocatorGroup = { start: number, end: number, first: string, firstDisplay: string, last: string, lastDisplay: string, };
