// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A footnote's byte range and number, so `supra note 4` resolves to the
 * authority first cited in note 4.
 */
export type NoteRange = { number: number, start: number, end: number, 
/**
 * Numbering sequence the note belongs to. Documents that restart note
 * numbering (per chapter, per part) repeat numbers across sequences; a
 * reference prefers a note in its own sequence.
 */
sequence: number, };
