// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The unit [`api`] reports offsets in. The Rust API always uses bytes.
 */
export type OffsetUnit = "byte" | "char" | "utf16";
