// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CitationStyle } from "./CitationStyle";
import type { NoteRange } from "./NoteRange";
import type { SupraMode } from "./SupraMode";

/**
 * Options for [`extract`].
 */
export type Options = { 
/**
 * Return the pinned Eyecite token view of the shared discovery result.
 * Native/Commonwealth occurrence discovery remains available by default.
 */
sourceOnly: boolean, 
/**
 * Omit citations with unresolved registry interpretations.
 */
removeAmbiguous: boolean, 
/**
 * Attach short forms, supra, ibid and references to their antecedents.
 */
resolve: boolean, 
/**
 * Group parallel citations.
 */
parallel: boolean, 
/**
 * Include the pinned source's specialized US citation forms in the shared
 * extractor. Literal citation cues prefilter their compiled patterns.
 */
extendedUs: boolean, 
/**
 * Treat each `\n\n`-separated block, or each entry of [`Options::notes`],
 * as a footnote whose number `supra note N` can refer to.
 */
notes: Array<NoteRange> | null, 
/**
 * Ordered jurisdiction preferences for ambiguous abbreviations, e.g.
 * `["ca", "uk"]`. An explicit court takes precedence. Empty is neutral.
 */
jurisdictionPriority: Array<string>, 
/**
 * ALR hint capture uses aggressive mode by default.
 */
supraHintMode: SupraMode, 
/**
 * Inferred and bare-note linking runs only in aggressive mode.
 */
supraLinkingMode: SupraMode, 
/**
 * The guides whose own forms are recognized; every guide's when absent.
 */
styles: Array<CitationStyle> | null, 
/**
 * Leave out what a document's own list or table of authorities holds: its entries list the
 * authorities the document cites elsewhere, and its tab numbers cite nothing.
 */
skipAuthorityLists: boolean, 
/**
 * Read a case's name with a pinpoint written before the case is first cited in full
 * ("Oakes at 138" … "R v Oakes, [1986] 1 SCR 103") as a reference to it, which has no
 * earlier citation. Eyecite reads references only after the full citation.
 */
earlyReferences: boolean, };
