// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParentheticalKind } from "./ParentheticalKind";
import type { Span } from "./Span";

export type Parenthetical = { kind: ParentheticalKind, span: Span, 
/**
 * The text inside the parentheses.
 */
content: string, };
