// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a trailing parenthetical carries.
 */
export type ParentheticalKind = "court" | "date" | "explanatory" | "source" | "record";
