// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parsed party names; a source may identify only one side.
 */
export type Parties = { plaintiff: string | null, defendant: string | null, };
