// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PinpointLayoutsRequest = { kind: string, values: Array<Array<string>>, style: string | null, };
