// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PinpointKind } from "./PinpointKind";
import type { Span } from "./Span";

/**
 * One located pinpoint. A range such as `paras 62-64` is one pinpoint with
 * `first = 62` and `last = 64`; a list such as `paras 20, 23 and 25` is three.
 */
export type Pinpoint = { kind: PinpointKind, span: Span, 
/**
 * The first locator of the range, normalized (`7(2)`, `12`, `xii`).
 */
first: string, 
/**
 * The last locator of a range; `None` for a single locator.
 */
last?: string | null, };
