// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Locator } from "./Locator";
import type { PinpointKind } from "./PinpointKind";

/**
 * `{kind: "paragraph", locators: [{first: "12", last: "14"}]}` →
 * `at paras 12-14`.
 */
export type PinpointRequest = { kind: PinpointKind, locators: Array<Locator>, };
