// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A whole annotation after offset mapping and markup treatment. `index`
 * identifies the input annotation so hosts can invoke callbacks with objects.
 */
export type PreparedAnnotation = { index: number, start: number, end: number, before: string, after: string, text: string, };
