// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Sources already identified by the caller. Targets are opaque authority or
 * source identifiers; matching never depends on a URL or retrieval status.
 */
export type ReferenceSource = { note: JsonValue, sequence: number | null, verbatim: string | null, target: string | null, 
/**
 * Names of the identified source, also inherited by references to it.
 */
names: Array<string>, short_form: string | null, short_form_norm: string | null, rule: string | null, };
