// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Authority } from "./Authority";
import type { Form } from "./Form";
import type { Format } from "./Format";

/**
 * The resolution-facing representation used by hosts with mutable citation
 * objects and custom resource types. Value tokens preserve host equality for
 * arbitrary metadata values; resource tokens preserve custom resource identity.
 */
export type ReferenceRecord = { form: Form, authority: Authority, format: Format | null, jurisdiction: string | null, reporter: string | null, volume: string | null, page: string | null, plaintiff: string | null, defendant: string | null, antecedentGuess: string | null, pinCite: string | null, nameValues: Array<number>, metadataValues: Array<number>, ambiguous: boolean, };
