// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferenceRecord } from "./ReferenceRecord";

export type ReferenceRequest = { citation: ReferenceRecord, fullCitations: Array<[ReferenceRecord, number | null]>, 
/**
 * The first citation of the resource returned by the preceding callback.
 */
previous: [ReferenceRecord, number] | null, };
