// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ALR's reference markers, preserving the note/n/nn pattern precedence.
 * Decimal strings let each binding retain Python's unbounded note integers.
 */
export type ReferenceInfo = { kind: string, notes: Array<string>, normalized: string, };
