// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReferenceSource } from "./ReferenceSource";

export type RegistryReferenceRequest = { text: string, registry: Array<ReferenceSource>, aggressive: boolean, };
