// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type RegistryVersion = { jurisdictions: number, courts: number, reporters: number, series: number, journals: number, 
/**
 * Reporter and journal entries by data source (`mcgill`, `reporters-db`, ...).
 */
sources: { [key in string]: number }, 
/**
 * Upstream data versions (`reporters-db`, `courts-db`) the generated
 * entries were built from, as pinned in `upstream.lock`.
 */
upstream: { [key in string]: JsonValue }, };
