// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `{}` returns the whole registry; `{table}` one table (`jurisdictions`,
 * `courts`, `reporters`, `series`, `journals`); `{table, surface}` the
 * entries of that table a surface form names, preferred first
 * (`{"table": "courts", "surface": "FCA"}` → Canadian `fca`, then `fca-au`;
 * `{"table": "reporters", "surface": "S.C.R."}` →
 * `[{"reporter": {...}, "canonical": "SCR"}]`).
 */
export type RegistryRequest = { table: string | null, surface: string | null, };
