// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";

export type ReporterHeaderRequest = { text: string, citations: Array<Citation>, };
