// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";
import type { NoteRange } from "./NoteRange";
import type { SourceAliasGroup } from "./SourceAliasGroup";
import type { SourcePart } from "./SourcePart";
import type { SplitTier } from "./SplitTier";
import type { SupraMode } from "./SupraMode";

/**
 * Resolve an existing citation list without extracting it again. Note ranges
 * and citation spans must use the same offset unit; resolution does not slice
 * the document, so no conversion or original text is needed.
 */
export type ResolveRequest = { citations: Array<Citation>, 
/**
 * Source boundaries emitted by extract, in the same offset unit as citations and notes.
 */
sourceParts: Array<SourcePart>, supraHintMode: SupraMode | null, supraLinkingMode: SupraMode | null, 
/**
 * See [`crate::Options::split_tier`].
 */
splitTier: SplitTier | null, 
/**
 * Citation indices in document reading order, when footnote anchors are known.
 */
readingOrder: Array<number> | null, notes: Array<NoteRange> | null, aliasGroups: Array<SourceAliasGroup>, };
