// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one non-full citation was (or was not) resolved.
 */
export type Resolution = { 
/**
 * [`Citation::index`] of the reference.
 */
index: number, 
/**
 * The authority it resolves to (a full citation's index, or its parallel
 * group's first index).
 */
antecedent: number | null, 
/**
 * Optional navigation URL of the matched source. Its absence has no
 * effect on association or authority identity.
 */
url?: string | null, 
/**
 * Matched source's origin, indexed into ExtractResponse.sourceParts.
 */
sourcePart?: number | null, 
/**
 * Machine-readable reason:
 *
 * * ibid: `ibid_previous`, `ibid_previous_note`, `ibid_after_multiple`, `ibid_after_unresolved`,
 *   `ibid_no_previous`, `ibid_invalid_pinpoint`;
 * * supra and references: `note_and_name`, `note_only`, `name_only`,
 *   `ambiguous_note`, `ambiguous_name`, `note_out_of_range`,
 *   `note_without_authority`, `note_name_conflict`, `no_match`, `no_hint`,
 *   `named_short_form` (linking mode [`SupraMode::Named`]), `acronym`;
 * * short forms: `short_reporter`, `short_name`, `short_ambiguous`,
 *   `short_no_match`;
 * * `unknown_form` for [`Form::Unknown`].
 */
reason: string, };
