// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";
import type { Resolution } from "./Resolution";

export type ResolveResponse = { citations: Array<Citation>, resolutions: Array<Resolution>, authorities: Array<Array<number>>, };
