// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One citation's complete alias closure from an installed source index.
 * An ambiguous index supplies only the citation's own key.
 */
export type SourceAliasGroup = { index: number, keys: Array<string>, };
