// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourcePart } from "./SourcePart";

export type SourceSplit = { status: string, parts: Array<SourcePart>, delimiters: Array<[number, number, string]>, reasons: Array<string>, };
