// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Span } from "./Span";

export type SourceCaseName = { fullSpanStart: number, fullSpanEnd: number | null, antecedentGuess: string | null, year: string | null, preCitation: Span | null, pinCite: Span | null, referenceSpan: Span | null, tokenSpan?: Span | null, pinCiteSpanEnd: number | null, parenthetical: string | null, };
