// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourcePart = { start: number, end: number, text: string, anchors: Array<string>, 
/**
 * ALR FootnotePart.link after host retrieval, before reference resolution.
 */
resolvedUrl?: string | null, extendedUs: boolean, 
/**
 * Exact source-grammar anchors in the same coordinate system as start/end.
 */
anchorSpans: Array<[number, number]>, };
