// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceReporter } from "./SourceReporter";

/**
 * Original reporters-db identity and dates; separate from registry corrections.
 */
export type SourceEdition = { short_name: string, reporter: SourceReporter, start: string | null, end: string | null, };
