// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourcePart } from "./SourcePart";

export type SourceFieldsRequest = { text: string | null, part: SourcePart | null, extendedUs: boolean | null, };
