// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceFields = { status: string, corrected: string, kind: string, link_candidate: string, pinpoint_fragments: Array<string>, 
/**
 * Decimal strings retain Python's unbounded integer representation.
 */
page_pinpoints: Array<string>, bare_citation: string, citation_with_style: string, short_form: string, reasons: Array<string>, };
