// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A range of the source text.
 */
export type Span = { start: number, end: number, text: string, };
