// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OffsetUnit } from "./OffsetUnit";

export type SplitSourcesRequest = { text: string, recallFirst: boolean, extendedUs: boolean, offsetUnit: OffsetUnit, };
