// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far a note splitter's references are linked where the evidence is incomplete
 * ([`Options::split_tier`]): `safe` links what a reference's own note and words support, `moderate`
 * also reads a supra by its name where the note it numbers cites another work, and `aggressive` also
 * continues an ibid from the last source of a note that names several.
 */
export type SplitTier = "safe" | "moderate" | "aggressive";
