// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Citation } from "./Citation";
import type { OffsetUnit } from "./OffsetUnit";
import type { Options } from "./Options";

export type UrlRequest = { citation: Citation | null, text: string | null, options: Options, offsetUnit: OffsetUnit, 
/**
 * `en` (default) or `fr`: the language of the page to link.
 */
language: string | null, 
/**
 * Append the anchor of a single pinpoint (`#par12`) when the source has one.
 */
anchor: boolean, };
