// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CitationUrl } from "./CitationUrl";

export type UrlResponse = { urls: Array<CitationUrl>, };
