// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrammarVersion } from "./GrammarVersion";
import type { RegistryVersion } from "./RegistryVersion";

export type VersionResponse = { 
/**
 * The `legal-citations` crate version.
 */
version: string, schemaVersion: number, keyVersion: string, grammar: GrammarVersion, registry: RegistryVersion, };
