import type { Citation } from "./bindings/Citation";
import type { Options } from "./bindings/Options";
import type { ExtractRequest } from "./bindings/ExtractRequest";
import type { ResolveRequest } from "./bindings/ResolveRequest";
import type { ResolveResponse } from "./bindings/ResolveResponse";
import type { KeyForTextResponse } from "./bindings/KeyForTextResponse";
import type { FormatRequest } from "./bindings/FormatRequest";
import type { FormatResponse } from "./bindings/FormatResponse";
import type { PinpointRequest } from "./bindings/PinpointRequest";
import type { UrlRequest } from "./bindings/UrlRequest";
import type { UrlResponse } from "./bindings/UrlResponse";
import type { AnnotateRequest } from "./bindings/AnnotateRequest";
import type { ExcerptClassification } from "./bindings/ExcerptClassification";
import type { VersionResponse } from "./bindings/VersionResponse";
import type { ApiError } from "./bindings/ApiError";
export type { Citation, Options as EngineOptions, VersionResponse as VersionInfo, ResolveResponse };
export type { OffsetUnit } from "./bindings/OffsetUnit";
export type { NoteRange } from "./bindings/NoteRange";
export type { ExtractResponse } from "./bindings/ExtractResponse";
export type { ReferenceInfo } from "./bindings/ReferenceInfo";
export type { CitationCorrection } from "./bindings/CitationCorrection";
export type { CorrectedCitation } from "./bindings/CorrectedCitation";
export type { PinpointKind } from "./bindings/PinpointKind";
export type { Annotation } from "./bindings/Annotation";
export type ExtractOptions = Partial<Options> & Partial<Omit<ExtractRequest, "text" | "options">>;
export type FormatOptions = Partial<Options> & Partial<Omit<FormatRequest, "text" | "citation" | "pinpoint" | "options">>;
export type AnnotateOptions = Partial<Options> & Partial<Omit<AnnotateRequest, "text" | "options">>;
export class LegalCitationsError extends Error { code: ApiError["code"]; }
export function init(input?: string | URL | Request | Response | BufferSource | WebAssembly.Module): Promise<void>;
export function initSync(module: BufferSource | WebAssembly.Module): void;
export function call(method: string, request?: object): unknown;
export function extract(text: string, options?: ExtractOptions): Citation[];
export function resolve(citations: Citation[], options?: Partial<Omit<ResolveRequest, "citations">>): ResolveResponse;
export function key(citation: Citation): string | null;
export function keyForText(text: string, options?: Partial<Options>): KeyForTextResponse;
export function format(input: Citation | string, options?: FormatOptions): FormatResponse["citations"];
export function formatPinpoint(kind: PinpointRequest["kind"], locators: PinpointRequest["locators"], options?: FormatOptions): string;
export function url(input: Citation | string, options?: Partial<Options> & Partial<Omit<UrlRequest, "text" | "citation" | "options">>): UrlResponse["urls"];
export function annotate(text: string, options?: AnnotateOptions): string;
export function clean(text: string, steps: string[]): string;
export function registry(table?: string, surface?: string): unknown;
export function classifyExcerpt(excerpt: string): ExcerptClassification;
export function hasCitation(text: string): boolean;
export function version(): VersionResponse;
